version: "3"

services:
  main_spring:
    container_name: main_spring
    build: ./BE/deep
    ports:
      - "8082:8088"
    volumes:
      - /spring:/image
    restart: on-failure
  main_react:
    container_name: main_react
    build: ./FE/deep
    ports:
      - "3002:3000"
    volumes:
      - /react:/image
    restart: on-failure
